name: pytorch-demo-app
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - cpuonly
  - pytorch=1.7
  - notebook
  - voila=0.2
  - pip:
    - torch-geometric
    - gdown
    - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-cluster
    - torch-spline-conv
    - torch-cluster
    - torch-scatter
    - torch-sparse
