name: pytorch-demo-app
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python=3.7
  - pip
  - notebook>=5.3
  - voila=0.2
  - scikit-learn=0.23.2
  - trimesh=3.8.1
  - networkx
  - pyglet
  - ipywidgets>=7.2
  - shapely
  - tornado=6.1
  - umap-learn=0.4
  - plotly=4.14.1
  - pip:
    - torch-geometric~=1.6
    - pytransform3d
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.7.0+cpu
    - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-cluster
    - torch-spline-conv
    - torch-cluster
    - torch-scatter
    - torch-sparse
